#!/usr/bin/env bash
# scripts/setup-cloudflare-tunnel.sh — put CCHQ behind a Cloudflare Tunnel so
# it's reachable from any device enrolled in your Cloudflare Zero Trust org
# (Cloudflare Mesh) at a private hostname — without exposing it to the public
# internet.
#
# Requires:
#   - cloudflared installed (brew install cloudflare/cloudflare/cloudflared)
#   - A Cloudflare account with Zero Trust enabled (free tier works)
#   - You've logged in at least once: cloudflared tunnel login
#
# What this does:
#   1. Creates a named tunnel called "cchq" (or reuses it if it already exists)
#   2. Writes a config file at ~/.cloudflared/config-cchq.yml
#   3. Starts the tunnel in the background
#
# The tunnel routes traffic from your Zero Trust private network to
# localhost:3000. Devices running the WARP client enrolled in your org can
# reach CCHQ over the tunnel's private IP or DNS route.
#
# Safe to re-run — reuses the existing tunnel and overwrites the config.

set -eu

PORT="${1:-3000}"
TUNNEL_NAME="cchq"
CONFIG_DIR="$HOME/.cloudflared"
CONFIG_FILE="$CONFIG_DIR/config-cchq.yml"

# ── preflight ────────────────────────────────────────────────────────────────

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared not found. Install it first:" >&2
  echo "  brew install cloudflare/cloudflare/cloudflared" >&2
  exit 1
fi

if [ ! -f "$CONFIG_DIR/cert.pem" ]; then
  echo "No Cloudflare cert found. Log in first:" >&2
  echo "  cloudflared tunnel login" >&2
  echo "(This opens a browser to authorize your Cloudflare account.)" >&2
  exit 1
fi

# ── create or reuse tunnel ───────────────────────────────────────────────────

if cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
  echo "Tunnel '$TUNNEL_NAME' already exists — reusing."
else
  echo "==> cloudflared tunnel create $TUNNEL_NAME"
  cloudflared tunnel create "$TUNNEL_NAME"
fi

# Grab the tunnel ID (needed for the credentials file path).
TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | grep "$TUNNEL_NAME" | awk '{print $1}')"

if [ -z "$TUNNEL_ID" ]; then
  echo "Could not determine tunnel ID. Run 'cloudflared tunnel list' to debug." >&2
  exit 1
fi

# ── write config ─────────────────────────────────────────────────────────────

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<YAML
# Auto-generated by scripts/setup-cloudflare-tunnel.sh
# Routes Cloudflare Mesh traffic to local CCHQ.
tunnel: $TUNNEL_ID
credentials-file: $CONFIG_DIR/$TUNNEL_ID.json

ingress:
  - service: http://localhost:$PORT
YAML

echo "Config written to $CONFIG_FILE"

# ── add a private network route (CGNAT range not needed — cloudflared handles
#    DNS-based routing via the ingress rule above). If you want IP-based
#    routing through WARP, uncomment and adjust:
#
#    cloudflared tunnel route ip add 10.0.0.0/24 $TUNNEL_NAME

# ── start tunnel ─────────────────────────────────────────────────────────────

echo "==> cloudflared tunnel --config $CONFIG_FILE run $TUNNEL_NAME"
cloudflared tunnel --config "$CONFIG_FILE" run "$TUNNEL_NAME" &
TUNNEL_PID=$!

# Give it a moment to connect.
sleep 2

if kill -0 "$TUNNEL_PID" 2>/dev/null; then
  echo
  cat <<EOF
Cloudflare Tunnel is up (PID $TUNNEL_PID).

Next steps — do these once in the Cloudflare Zero Trust dashboard:

  1. Go to Networks > Tunnels and confirm "$TUNNEL_NAME" is healthy.
  2. Add a Private Network route so enrolled WARP devices can reach it:
       Networks > Tunnels > $TUNNEL_NAME > Private Network tab
       Add your Mac's local subnet (e.g. 192.168.1.0/24) or a specific IP.
  3. Enroll devices: install the WARP client on each device, log in to your
     Zero Trust org, and verify they appear under My Team > Devices.

Once enrolled, devices reach CCHQ through the WARP client — no public URL,
no port forwarding, no DNS record needed for private access.

Stop with:  ./scripts/stop-cloudflare-tunnel.sh
Logs:       cloudflared tunnel --config $CONFIG_FILE run $TUNNEL_NAME
              (run in foreground to see logs)
EOF
else
  echo "Tunnel process exited unexpectedly. Run in foreground to debug:" >&2
  echo "  cloudflared tunnel --config $CONFIG_FILE run $TUNNEL_NAME" >&2
  exit 1
fi
